contentColumnType: text
fieldGroup: a6b0a29b-fbfa-4071-a468-1682450ea273
handle: addressRegion
instructions: ''
name: 'Address Region'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: Victoria
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
