contentColumnType: text
fieldGroup: f236671b-2123-4941-a279-c5f723c68bfa
handle: BeforeHead
instructions: 'Include any tags that should run before the closing head tag. These may include live chat widgets, and calendar schedulers.'
name: 'Code to run before </head>'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
