contentColumnType: string(255)
fieldGroup: 2d9f761f-8cb5-4e4b-bb93-e87bc8e96fbd
handle: instagramProfile
instructions: ''
name: 'Instagram Profile'
searchable: false
settings:
  maxLength: '255'
  placeholder: 'https://instagram.com/barayamal3'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
