contentColumnType: string(255)
fieldGroup: 2d9f761f-8cb5-4e4b-bb93-e87bc8e96fbd
handle: linkedinPage
instructions: ''
name: 'LinkedIn Page'
searchable: false
settings:
  maxLength: '255'
  placeholder: 'https://www.linkedin.com/company/barayamal'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
