contentColumnType: text
fieldGroup: a6b0a29b-fbfa-4071-a468-1682450ea273
handle: streetAddress
instructions: ''
name: 'Street Address'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: '710 Collins Street'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
